# Generated by Django 4.1.7 on 2023-02-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='parent',
            new_name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
            preserve_default=False,
        ),
    ]
