# Generated by Django 4.1.7 on 2023-02-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_parent_link_menu_menu_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='menu.menu'),
        ),
    ]
