# Generated by Django 4.1.7 on 2023-02-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_link_url_alter_menu_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
