# Generated by Django 4.2.6 on 2023-10-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_menu_parent_alter_menu_name_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='menu.menu'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
