# Generated by Django 4.2.6 on 2023-10-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_parent_delete_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu'),
        ),
    ]
